### PR TITLE
Add benchmark result for kafka connect

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
Rebased.

**Review by cosmo0920 — CHANGES_REQUESTED** [review]
w/o TLS and w/ TLS result tables are broken.
Could you fix them?
[Rendered](https://github.com/okkez/fluentd-benchmark/blob/292bc0d32c351874e70ed2338bbe1e8d5aff8457/kafka-connect/README.md)

**Comment by okkez** [comment]
Fixed.

**Review by cosmo0920 — APPROVED** [review]
:+1:

**Pull request merged**
